"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-08-22 02:44:21.543737
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# The mission-key sequence backing next_mission_key() -> "FND-<n>". Starts past the seeded
# fixtures (FND-142/150) so generated keys never collide with them.
MISSION_KEY_SEQ = "mission_key_seq"
MISSION_KEY_START = 151

# Tenant tables that get an RLS policy keyed on current_setting('app.workspace_id') (Canon
# §13.2). `steps` is reached only via a tenant-scoped run, so it inherits isolation and is
# excluded here. This migration is the single source of truth for the RLS policy set.
RLS_TABLES = [
    "missions", "runs", "events", "blockers", "agents", "model_connections", "skills",
    "memories", "integrations", "autonomy_policies",
]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('org_id', sa.String(length=40), nullable=True),
    sa.Column('workspace_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('role_key', sa.String(length=16), nullable=False),
    sa.Column('model_binding', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('skills', sa.JSON(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agents_workspace_id'), 'agents', ['workspace_id'], unique=False)
    op.create_table('autonomy_policies',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('workspace_id', sa.String(length=40), nullable=False),
    sa.Column('autonomy', sa.String(length=16), nullable=False),
    sa.Column('gates', sa.JSON(), nullable=False),
    sa.Column('spend_threshold_cents', sa.Integer(), nullable=False),
    sa.Column('budget_cap_cents', sa.Integer(), nullable=False),
    sa.Column('max_parallel_agents', sa.Integer(), nullable=False),
    sa.Column('guardrails', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_autonomy_policies_workspace_id'), 'autonomy_policies', ['workspace_id'], unique=True)
    op.create_table('blockers',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('org_id', sa.String(length=40), nullable=True),
    sa.Column('workspace_id', sa.String(length=40), nullable=True),
    sa.Column('mission_id', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('severity', sa.String(length=8), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('model_connection_id', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blockers_mission_id'), 'blockers', ['mission_id'], unique=False)
    op.create_index(op.f('ix_blockers_workspace_id'), 'blockers', ['workspace_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('run_id', sa.String(length=40), nullable=True),
    sa.Column('mission_id', sa.String(length=40), nullable=True),
    sa.Column('workspace_id', sa.String(length=40), nullable=False),
    sa.Column('agent_role', sa.String(length=16), nullable=True),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('seq', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_mission_id'), 'events', ['mission_id'], unique=False)
    op.create_index(op.f('ix_events_run_id'), 'events', ['run_id'], unique=False)
    op.create_index(op.f('ix_events_seq'), 'events', ['seq'], unique=False)
    op.create_index(op.f('ix_events_workspace_id'), 'events', ['workspace_id'], unique=False)
    op.create_table('integrations',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('org_id', sa.String(length=40), nullable=True),
    sa.Column('workspace_id', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('credential_ref', sa.String(length=400), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integrations_workspace_id'), 'integrations', ['workspace_id'], unique=False)
    op.create_table('memories',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('org_id', sa.String(length=40), nullable=True),
    sa.Column('workspace_id', sa.String(length=40), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('links', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memories_workspace_id'), 'memories', ['workspace_id'], unique=False)
    op.create_table('missions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('key', sa.String(length=32), nullable=False),
    sa.Column('org_id', sa.String(length=40), nullable=True),
    sa.Column('workspace_id', sa.String(length=40), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('ext_ref', sa.String(length=64), nullable=True),
    sa.Column('priority', sa.String(length=4), nullable=False),
    sa.Column('stage', sa.String(length=16), nullable=False),
    sa.Column('autonomy', sa.String(length=16), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.String(length=40), nullable=True),
    sa.Column('branch', sa.String(length=200), nullable=True),
    sa.Column('pr_url', sa.String(length=400), nullable=True),
    sa.Column('labels', sa.JSON(), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_missions_key'), 'missions', ['key'], unique=True)
    op.create_index(op.f('ix_missions_stage'), 'missions', ['stage'], unique=False)
    op.create_index(op.f('ix_missions_workspace_id'), 'missions', ['workspace_id'], unique=False)
    op.create_table('model_connections',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('org_id', sa.String(length=40), nullable=True),
    sa.Column('workspace_id', sa.String(length=40), nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('models', sa.JSON(), nullable=False),
    sa.Column('endpoint', sa.String(length=400), nullable=True),
    sa.Column('credential_ref', sa.String(length=400), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_connections_workspace_id'), 'model_connections', ['workspace_id'], unique=False)
    op.create_table('runs',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('mission_id', sa.String(length=40), nullable=False),
    sa.Column('workspace_id', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('autonomy', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cost_cents', sa.Integer(), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runs_mission_id'), 'runs', ['mission_id'], unique=False)
    op.create_index(op.f('ix_runs_workspace_id'), 'runs', ['workspace_id'], unique=False)
    op.create_table('skills',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('org_id', sa.String(length=40), nullable=True),
    sa.Column('workspace_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('trigger', sa.Text(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('auto_invoke', sa.Boolean(), nullable=False),
    sa.Column('installed', sa.Boolean(), nullable=False),
    sa.Column('uses', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_workspace_id'), 'skills', ['workspace_id'], unique=False)
    op.create_table('steps',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('run_id', sa.String(length=40), nullable=False),
    sa.Column('phase', sa.String(length=24), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('agent_role', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('seq', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_steps_run_id'), 'steps', ['run_id'], unique=False)
    op.create_index(op.f('ix_steps_seq'), 'steps', ['seq'], unique=False)
    # ### end Alembic commands ###

    # Hand-added (autogenerate can't infer these): the mission-key sequence and RLS.
    _create_mission_key_sequence()
    _enable_row_level_security()


def downgrade() -> None:
    _drop_mission_key_sequence()  # RLS policies are dropped automatically with their tables
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_steps_seq'), table_name='steps')
    op.drop_index(op.f('ix_steps_run_id'), table_name='steps')
    op.drop_table('steps')
    op.drop_index(op.f('ix_skills_workspace_id'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_runs_workspace_id'), table_name='runs')
    op.drop_index(op.f('ix_runs_mission_id'), table_name='runs')
    op.drop_table('runs')
    op.drop_index(op.f('ix_model_connections_workspace_id'), table_name='model_connections')
    op.drop_table('model_connections')
    op.drop_index(op.f('ix_missions_workspace_id'), table_name='missions')
    op.drop_index(op.f('ix_missions_stage'), table_name='missions')
    op.drop_index(op.f('ix_missions_key'), table_name='missions')
    op.drop_table('missions')
    op.drop_index(op.f('ix_memories_workspace_id'), table_name='memories')
    op.drop_table('memories')
    op.drop_index(op.f('ix_integrations_workspace_id'), table_name='integrations')
    op.drop_table('integrations')
    op.drop_index(op.f('ix_events_workspace_id'), table_name='events')
    op.drop_index(op.f('ix_events_seq'), table_name='events')
    op.drop_index(op.f('ix_events_run_id'), table_name='events')
    op.drop_index(op.f('ix_events_mission_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_blockers_workspace_id'), table_name='blockers')
    op.drop_index(op.f('ix_blockers_mission_id'), table_name='blockers')
    op.drop_table('blockers')
    op.drop_index(op.f('ix_autonomy_policies_workspace_id'), table_name='autonomy_policies')
    op.drop_table('autonomy_policies')
    op.drop_index(op.f('ix_agents_workspace_id'), table_name='agents')
    op.drop_table('agents')
    # ### end Alembic commands ###


def _create_mission_key_sequence() -> None:
    op.execute(f"CREATE SEQUENCE IF NOT EXISTS {MISSION_KEY_SEQ} START {MISSION_KEY_START}")


def _drop_mission_key_sequence() -> None:
    op.execute(f"DROP SEQUENCE IF EXISTS {MISSION_KEY_SEQ}")


def _enable_row_level_security() -> None:
    """Enable + FORCE RLS and install the workspace-isolation policy on each tenant table.

    FORCE makes the policy bind even for the table owner; the app connects as a non-superuser
    role so RLS is never bypassed (Canon §13.2).
    """
    for table in RLS_TABLES:
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(f"DROP POLICY IF EXISTS ws_isolation ON {table}")
        op.execute(
            f"CREATE POLICY ws_isolation ON {table} "
            "USING (workspace_id = current_setting('app.workspace_id', true)) "
            "WITH CHECK (workspace_id = current_setting('app.workspace_id', true))"
        )
